{ config, ... }: {
  discord = {
    enable = true;

    settings = {
      enable-devtools = true;

      # settings generated by discord
      offloadAdmControls = true;
      enableHardwareAcceleration = true;
      trayBalloonShown = true;
      chromiumSwitches = { };
      BACKGROUND_COLOR = "#121214";
    };

    openasar.enable = true;
    vencord = {
      enable = true;
      customPlugins = [ ./MudaeBot.ts ];
    };
  };
  hypr.land.settings.bind = with config.lib.hyprland.dispatchers; [
    [ "SUPER + D" (exec "${config.discord.finalPackage}/bin/discord --enable-features=UseOzonePlatform --ozone-platform=wayland") ]
  ];
}
