{ lib, ... }: {
  discord = {
    enable = lib.mkDefault true;

    settings = {
      enable-devtools = true;

      # settings generated by discord
      offloadAdmControls = true;
      enableHardwareAcceleration = true;
      trayBalloonShown = true;
    };

    openasar.enable = true;
    vencord.enable = true;
  };
}
